name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag k8s-app:latest

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Tag the Docker image
      run: docker tag ghcr.io/${{ github.repository_owner }}/k8s-app:latest
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/k8s-app:latest