name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag k8s-app:latest

    - name: Push the Docker image
      run: |
      echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      docker tag k8s-app:latest "${{ secrets.DOCKER_USERNAME }}/k8s-app:latest"
      docker push "${{ secrets.DOCKER_USERNAME }}/k8s-app:latest"
