name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SHORT_SHA: ${{ needs.set-env.outputs.short_sha }}

jobs:

  set-env:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.short-sha.outputs.sha }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Set Short SHA as Output
      id: short-sha
      run: echo "::set-output name=sha::$(echo ${{ github.sha }} | cut -c1-7)"

  build:
    needs: set-env
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag k8s-app:${{ env.SHORT_SHA }}

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin